[phases.setup]
nixPkgs = ["dart", "flutter"]

[phases.install]
cmds = ["flutter pub get"]

[phases.build]
cmds = ["flutter build web --release"]

[start]
cmd = "cd build/web && dart pub global activate dhttpd && dhttpd --path=."
