[phases.setup]
nixPkgs = ["dart", "flutter"]
aptPkgs = ["curl", "git", "unzip", "xz-utils", "libglu1-mesa"]

[phases.install]
cmds = ["flutter pub get"]

[phases.build]
cmds = ["flutter build web --release"]

[start]
cmd = "dart pub global activate dhttpd && dhttpd --path=./build/web --port=8080"
